// Package lockfile handles reading and writing Prolfile.lock.
package lockfile

import (
	"bytes"
	"fmt"
	"os"
	"sort"

	"github.com/BurntSushi/toml"
	"github.com/prolm/prolm/internal/atomicfile"
	"github.com/prolm/prolm/pkg/prolfile"
)

// LockFileName is the conventional name for the lockfile.
const LockFileName = "Prolfile.lock"

// lockfileHeader is prepended to every saved lockfile.
const lockfileHeader = "# This file is auto-generated by prolm. Do not edit by hand.\n" +
	"# Commit this file to version control for reproducible installs.\n\n"

// LockVersionTooNewError indicates the lockfile's lock_version exceeds what
// this version of prolm supports.
type LockVersionTooNewError struct {
	Found     int
	Supported int
}

func (e *LockVersionTooNewError) Error() string {
	return fmt.Sprintf(
		"Prolfile.lock requires lock_version %d, but prolm only supports version %d; run `prolm self-update` to upgrade",
		e.Found, e.Supported,
	)
}

// GitConflictError indicates the lockfile contains Git merge conflict markers.
type GitConflictError struct {
	Path string
}

func (e *GitConflictError) Error() string {
	return fmt.Sprintf(
		"Prolfile.lock at %s contains Git merge conflict markers; run `prolm install` to re-resolve from Prolfile.toml, or resolve conflicts manually",
		e.Path,
	)
}

// Load reads and parses a Prolfile.lock at the given path.
//
// If the file does not exist, it returns (nil, nil) — this signals a first
// install where no lockfile has been created yet.
//
// Before parsing, the raw content is scanned for Git merge conflict markers
// (<<<<<<<, =======, >>>>>>>) so the user gets a clear error instead of a
// confusing TOML parse failure.
func Load(path string) (*prolfile.LockFile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}

	if containsConflictMarkers(data) {
		return nil, &GitConflictError{Path: path}
	}

	var lf prolfile.LockFile
	if err := toml.Unmarshal(data, &lf); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}

	if err := checkLockVersion(lf.Meta.LockVersion); err != nil {
		return nil, err
	}

	return &lf, nil
}

// Save writes a LockFile to the given path with deterministic output.
//
// Packages are sorted by name. The lockfile key order (name, version, source,
// url, checksum, dependencies) is guaranteed by the LockEntry struct field
// order in pkg/prolfile/types.go.
//
// Writes are atomic (SEC-8): content is written to a temporary file first,
// then renamed into place. A crash mid-write never leaves a partial lockfile.
//
// Save does not mutate lf or its Packages slice.
func Save(path string, lf *prolfile.LockFile) error {
	// Copy the slice so we don't mutate the caller's LockFile.
	packages := make([]prolfile.LockEntry, len(lf.Packages))
	copy(packages, lf.Packages)

	// Sort packages by name for deterministic output.
	sort.SliceStable(packages, func(i, j int) bool {
		return packages[i].Name < packages[j].Name
	})

	// Ensure Dependencies is never nil so the encoder always emits the key.
	// Operates on the local copy only.
	for i := range packages {
		if packages[i].Dependencies == nil {
			packages[i].Dependencies = []string{}
		}
	}

	// Build a shallow copy of lf with the sorted, normalised packages.
	out := *lf
	out.Packages = packages

	var buf bytes.Buffer
	enc := toml.NewEncoder(&buf)
	if err := enc.Encode(out); err != nil {
		return fmt.Errorf("encoding Prolfile.lock: %w", err)
	}

	content := lockfileHeader + buf.String()

	// Atomic write (SEC-8).
	if err := atomicfile.Write(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("saving lockfile: %w", err)
	}
	return nil
}

// IsEmpty reports whether the lockfile is absent or contains no packages.
func IsEmpty(lf *prolfile.LockFile) bool {
	return lf == nil || len(lf.Packages) == 0
}

// containsConflictMarkers checks for Git merge conflict markers in raw data.
// The <<<<<<< and >>>>>>> markers use HasPrefix because Git appends branch
// names after them. The ======= separator is matched exactly (after trimming
// whitespace) to avoid false positives on lines that merely start with "=".
func containsConflictMarkers(data []byte) bool {
	for _, line := range bytes.Split(data, []byte("\n")) {
		trimmed := bytes.TrimSpace(line)
		if bytes.HasPrefix(trimmed, []byte("<<<<<<<")) ||
			bytes.Equal(trimmed, []byte("=======")) ||
			bytes.HasPrefix(trimmed, []byte(">>>>>>>")) {
			return true
		}
	}
	return false
}

func checkLockVersion(version int) error {
	if version == 0 {
		return fmt.Errorf("Prolfile.lock is missing [meta].lock_version")
	}
	if version > prolfile.CurrentLockVersion {
		return &LockVersionTooNewError{
			Found:     version,
			Supported: prolfile.CurrentLockVersion,
		}
	}
	return nil
}
